sudo: required
language: go

services:
  - docker

env:
  global:
    - IMAGE_NAME=cloudflare-ddns
    - VERSION=$TRAVIS_TAG

script:
- echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
- docker build . -t "$IMAGE_NAME"

deploy:
  provider: script
  script: docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest" && docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${version}" && docker push hugomd:$IMAGE_NAME
  on:
    branch: master
    tags: true
